# Generated by Django 5.0.4 on 2026-08-31 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hr', '0007_payroll_advance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='attendancestatus',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_statuses', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.department'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profiles', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='leaverequeststatus',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_statuses', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='payrollrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_rules', to='core.organization'),
        ),
    ]
