"""
Django settings for xenocrm project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-8hy1oc1j-%q^tw30p=az*gml$e9u!5wy^umtrghc4!b9@#gkpp')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])
ALLOWED_HOSTS.extend(['.onrender.com', 'xeno.xenotrix.in', 'www.xeno.xenotrix.in', 'localhost', '127.0.0.1'])
if '*' in ALLOWED_HOSTS or env.bool('ALLOW_ALL_HOSTS', default=False):
    ALLOWED_HOSTS = ['*']

RENDER_EXTERNAL_HOSTNAME = env('RENDER_EXTERNAL_HOSTNAME', default=None)
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=['https://xeno.xenotrix.in', 'https://www.xeno.xenotrix.in', 'https://*.xenotrix.in', 'https://*.onrender.com'])
CSRF_TRUSTED_ORIGINS.extend([
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:8001',
    'http://127.0.0.1:8001',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'http://localhost',
    'http://127.0.0.1'
])
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

import sys

if not DEBUG and 'test' not in sys.argv:
    # Tell Django it's secure if Render's proxy forwards it as HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=True)
    CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=True)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'core',
    'leads',
    'services',
    'support',
    'projects',
    'activities',
    'campaigns',
    'content_tracker',
    'finance',
    'hr',
    'crm',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xenocrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'crm.context_processors.unread_notifications_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'xenocrm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
        ssl_require=True,
    )
}


# Password hashing — plain text (no hashing), for development/internal use only
PASSWORD_HASHERS = [
    'crm.hashers.PlainTextPasswordHasher',
]

# Password validation — disabled
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

import whitenoise.storage
_orig_url_converter = whitenoise.storage.CompressedManifestStaticFilesStorage.url_converter
def _patched_url_converter(self, name, hashed_files, template=None):
    _converter = _orig_url_converter(self, name, hashed_files, template)
    def _safe_converter(matchobj):
        try:
            return _converter(matchobj)
        except ValueError:
            return matchobj.groupdict()["matched"]
    return _safe_converter
whitenoise.storage.CompressedManifestStaticFilesStorage.url_converter = _patched_url_converter

_orig_compress = whitenoise.storage.CompressedManifestStaticFilesStorage.compress_files
def _safe_compress(self, paths):
    iterator = _orig_compress(self, paths)
    while True:
        try:
            yield next(iterator)
        except StopIteration:
            break
        except FileNotFoundError:
            pass
whitenoise.storage.CompressedManifestStaticFilesStorage.compress_files = _safe_compress

STORAGES = {
    'default': {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage' if 'test' in sys.argv else 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
WHITENOISE_MANIFEST_STRICT = False

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

import cloudinary
import os

cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    secure=True
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# Email Configuration (SMTP with Console fallback if credentials are not configured)
EMAIL_BACKEND = env(
    'EMAIL_BACKEND', 
    default='django.core.mail.backends.smtp.EmailBackend' if env('EMAIL_HOST_USER', default='') else 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=env('EMAIL_HOST_USER', default='noreply@xenocrm.com'))
SERVER_EMAIL = env('SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)

# WhatsApp Business Meta Cloud API Settings
WHATSAPP_CLOUD_API_TOKEN = env('WHATSAPP_CLOUD_API_TOKEN', default='EAAUDkJUZBQyMBSRMGlo5MUDObbvNk1LrO9mvmZBEHsDs09Of235bQoOJGX2oHInJwwqTjYSTuxjvCOHnf76p70JZBnZBTOpdfCLWOmabho7EXIvKLeIxFUiyyff09bMo29dRHRAivcakReol9RtlavZAK0JDjKgSgZAw5MkpEjRRZA8C245FuxMYPZAPvj91EU0RsEnTpIpEePS1yNV2T6oxkPELl0HI2ZBjQenSI10o3l9cCtJKMqrqlbCr0lvhUTmZBIlPBjHeEJLUl9PBt9I3zOdYCCubK1v4vOvwZDZD')
WHATSAPP_PHONE_NUMBER_ID = env('WHATSAPP_PHONE_NUMBER_ID', default='1249495338254585')
WHATSAPP_BUSINESS_ACCOUNT_ID = env('WHATSAPP_BUSINESS_ACCOUNT_ID', default='1753452545807653')
